### ISSUE TITLE
player-mpris-tail error

### ISSUE THREAD

**Issue by mxmilkb** [polybar/polybar-scripts#220]
```
Traceback (most recent call last):
  File "/usr/share/polybar/scripts/player-mpris-tail.py", line 500, in <module>
    PlayerManager(blacklist = args.blacklist)
  File "/usr/share/polybar/scripts/player-mpris-tail.py", line 32, in __init__
    self.refreshPlayerList()
  File "/usr/share/polybar/scripts/player-mpris-tail.py", line 84, in refreshPlayerList
    self.addPlayer(player_bus_name)
  File "/usr/share/polybar/scripts/player-mpris-tail.py", line 90, in addPlayer
    player = Player(self._session_bus, bus_name, owner = owner, connect = self._connect, _print = self.print)
  File "/usr/share/polybar/scripts/player-mpris-tail.py", line 196, in __init__
    self.refreshMetadata()
  File "/usr/share/polybar/scripts/player-mpris-tail.py", line 246, in refreshMetadata
    self._parseMetadata()
  File "/usr/share/polybar/scripts/player-mpris-tail.py", line 277, in _parseMetadata
    _year       = self.metadata['date'][0:4] if len(_date) else ''
KeyError: 'date'
```

I thought it might have been the exec line I had set just the day before, but I get that error output when I run the script in the terminal.

`exec = /usr/share/polybar/scripts/player-mpris-tail.py -f '{:artist:t35:{artist}:}{:artist: - :}{:year:{year} - :}{:album:t20:{album}:}{:album: - :}{:t20:{title}:}  %{A1:/usr/share/polybar/scripts/player-mpris-tail.py previous:}⏮%{A} %{A1:/usr/share/polybar/scripts/player-mpris-tail.py play-pause:}{icon-reversed}%{A} %{A1:/usr/share/polybar/scripts/player-mpris-tail.py next:}⏭%{A}'`

The information was coming from mpv mpris.so, Clementine and Goodvibes.

**Comment by x70b1** [comment]
@Cybolic We have another one, but it seems not to be a probelm with spotify.
Can you take a look on it?
